In [70]:
#Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array

import numpy as np
#import pandas as pd

def function():
    arr=np.array([1,2,7,107])
    print(arr)
    print(f"size = {arr.size}")
    print(f"Bytes={arr.nbytes}")

In [25]:
function()

[  1   2   7 107]
size = 4
Bytes=32


In [34]:
#Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

x = np.array([3, 5])
y = np.array([2, 5])

print("Comparison - greater")
print(np.greater(x, y))

print("Comparison - greater_equal")
print(np.greater_equal(x, y))


print("Comparison - less")
print(np.less(x, y))

print("Comparison - less_equal")
print(np.less_equal(x, y)) 

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [44]:
#Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

arr2 = np.zeros(10)
print(arr2)

arr2 = np.ones(10)
print(arr2)

arr2 = np.ones(10)*5
print(arr2)

arr2 = np.ones(10)*10
print(arr2)

arr2 = np.ones(10)*20
print(arr2)

arr2 = np.ones(10)*50
print(arr2)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [49]:
#Write a NumPy program to create an array of integers from 50 to 95.

arr3 = np.arange(30,71)
print(arr3)



[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [50]:
#Write a NumPy program to create an array of integers from 50 to 95.

arr4 = np.arange(50,96)
print(arr4)



[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [54]:
#Write a NumPy program to create an array of all even integers from 20 to 80.

arr5=np.arange(20,81,2)
print(arr5)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [57]:
#Write a NumPy program to create an array of all odd integers from 20 to 80.

arr6=np.arange(20+1,80,2)
print(arr6)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [58]:
#Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

arr7=np.random.randint(10,40,15)
print(arr7)

[14 11 18 37 23 32 32 12 27 22 37 32 13 24 34]


In [59]:
#Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

arr8=np.random.randint(30,50,10)
print(arr8)


[37 40 39 43 42 49 41 34 40 41]


In [61]:
#Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

arr9=np.random.randint(50,90,20)
print(arr9)

[86 61 60 64 63 72 85 54 60 75 73 69 64 78 51 75 69 67 61 76]


In [63]:
#Create any two arrays & perform various mathematical operations.
 #   i.e. Addition, Substraction, Multiplication, Divide.

a1=np.array([10,20,30,40])
a2=np.array([50,60,70,80])
print(f"arr={a1}")
print(f"arr={a2}")
print(a1+a2)


arr=[10 20 30 40]
arr=[50 60 70 80]
[ 60  80 100 120]


In [73]:
 #Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

m = np.arange(10, 22).reshape((3, 4))
print(m)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [74]:

#Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
#Write a NumPy program to find the number of rows and columns in a given     matrix. 

mat = np.array([[9, 9, 9], [8, 8, 8]])
 
dimensions = mat.shape
rows, columns = dimensions
 
print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3


In [76]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

import numpy as np


x = np.diag([1, 2, 3, 4, 5])
print(x) 

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
